Models/CompanyDescriptions.cs
using System;
using System.Collections.Generic;

namespace CareerCloudMVCCore2.Models
{
    public partial class CompanyDescriptions
    {
        public Guid Id { get; set; }
        public Guid Company { get; set; }
        public string LanguageId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyDescription { get; set; }
        public byte[] TimeStamp { get; set; }

        public virtual CompanyProfiles CompanyNavigation { get; set; }
        public virtual SystemLanguageCodes Language { get; set; }
    }
}

Models/CompanyJobEducations.cs
using System;
using System.Collections.Generic;

namespace CareerCloudMVCCore2.Models
{
    public partial class CompanyJobEducations
    {
        public Guid Id { get; set; }
        public Guid Job { get; set; }
        public string Major { get; set; }
        public short Importance { get; set; }
        public byte[] TimeStamp { get; set; }

        public virtual CompanyJobs JobNavigation { get; set; }
    }
}

Models/CompanyJobSkills.cs
using System;
using System.Collections.Generic;

namespace CareerCloudMVCCore2.Models
{
    public partial class CompanyJobSkills
    {
        public Guid Id { get; set; }
        public Guid Job { get; set; }
        public string Skill { get; set; }
        public string SkillLevel { get; set; }
        public int Importance { get; set; }
        public byte[] TimeStamp { get; set; }

        public virtual CompanyJobs JobNavigation { get; set; }
    }
}

Controllers/CompanyJobEducationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CareerCloudMVCCore2.Models;

namespace CareerCloudMVCCore2.Controllers
{
    public class CompanyJobEducationsController : Controller
    {
        private readonly JOB_PORTAL_DBContext _context;

        public CompanyJobEducationsController(JOB_PORTAL_DBContext context)
        {
            _context = context;
        }

        // GET: CompanyJobEducations
        public async Task<IActionResult> Index()
        {
            var jOB_PORTAL_DBContext = _context.CompanyJobEducations.Include(c => c.JobNavigation);
            return View(await jOB_PORTAL_DBContext.ToListAsync());
        }

        // GET: CompanyJobEducations/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobEducations = await _context.CompanyJobEducations
                .Include(c => c.JobNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyJobEducations == null)
            {
                return NotFound();
            }

            return View(companyJobEducations);
        }

        // GET: CompanyJobEducations/Create
        public IActionResult Create(Guid id)
        {
            ViewData["Job"] = new SelectList(_context.CompanyJobs, "Id", "Id");
            return View();
        }

        // POST: CompanyJobEducations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Major,Importance")] CompanyJobEducations companyJobEducations,Guid id)
        {
            companyJobEducations.Job = id;
            if (ModelState.IsValid)
            {
                companyJobEducations.Id = Guid.NewGuid();
                _context.Add(companyJobEducations);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index),"CompanyProfiles");
            }
            ViewData["Job"] = new SelectList(_context.CompanyJobs, "Id", "Id", companyJobEducations.Job);
            return View(companyJobEducations);
        }

        // GET: CompanyJobEducations/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobEducations = await _context.CompanyJobEducations.FindAsync(id);
            if (companyJobEducations == null)
            {
                return NotFound();
            }
            ViewData["Job"] = new SelectList(_context.CompanyJobs, "Id", "Id", companyJobEducations.Job);
            return View(companyJobEducations);
        }

        // POST: CompanyJobEducations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Job,Major,Importance,TimeStamp")] CompanyJobEducations companyJobEducations)
        {
            if (id != companyJobEducations.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(companyJobEducations);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyJobEducationsExists(companyJobEducations.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Job"] = new SelectList(_context.CompanyJobs, "Id", "Id", companyJobEducations.Job);
            return View(companyJobEducations);
        }

        // GET: CompanyJobEducations/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobEducations = await _context.CompanyJobEducations
                .Include(c => c.JobNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyJobEducations == null)
            {
                return NotFound();
            }

            return View(companyJobEducations);
        }

        // POST: CompanyJobEducations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var companyJobEducations = await _context.CompanyJobEducations.FindAsync(id);
            _context.CompanyJobEducations.Remove(companyJobEducations);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyJobEducationsExists(Guid id)
        {
            return _context.CompanyJobEducations.Any(e => e.Id == id);
        }
    }
}

Controllers/CompanyJobSkillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CareerCloudMVCCore2.Models;

namespace CareerCloudMVCCore2.Controllers
{
    public class CompanyJobSkillsController : Controller
    {
        private readonly JOB_PORTAL_DBContext _context;

        public CompanyJobSkillsController(JOB_PORTAL_DBContext context)
        {
            _context = context;
        }

        // GET: CompanyJobSkills
        public async Task<IActionResult> Index()
        {
            var jOB_PORTAL_DBContext = _context.CompanyJobSkills.Include(c => c.JobNavigation);
            return View(await jOB_PORTAL_DBContext.ToListAsync());
        }

        // GET: CompanyJobSkills/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobSkills = await _context.CompanyJobSkills
                .Include(c => c.JobNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyJobSkills == null)
            {
                return NotFound();
            }

            return View(companyJobSkills);
        }

        // GET: CompanyJobSkills/Create
        public IActionResult Create(Guid guid)
        {
            ViewData["Job"] = new SelectList(_context.CompanyJobs, "Id", "Id");
            return View();
        }

        // POST: CompanyJobSkills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Skill,SkillLevel,Importance")] CompanyJobSkills companyJobSkills,Guid id)
        {
            companyJobSkills.Job = id;
            if (ModelState.IsValid)
            {
                companyJobSkills.Id = Guid.NewGuid();
                _context.Add(companyJobSkills);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create),"CompanyJobEducations", new {id=companyJobSkills.Job});
            }
            ViewData["Job"] = new SelectList(_context.CompanyJobs, "Id", "Id", companyJobSkills.Job);
            return View(companyJobSkills);
        }

        // GET: CompanyJobSkills/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobSkills = await _context.CompanyJobSkills.FindAsync(id);
            if (companyJobSkills == null)
            {
                return NotFound();
            }
            ViewData["Job"] = new SelectList(_context.CompanyJobs, "Id", "Id", companyJobSkills.Job);
            return View(companyJobSkills);
        }

        // POST: CompanyJobSkills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Job,Skill,SkillLevel,Importance,TimeStamp")] CompanyJobSkills companyJobSkills)
        {
            if (id != companyJobSkills.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(companyJobSkills);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyJobSkillsExists(companyJobSkills.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Job"] = new SelectList(_context.CompanyJobs, "Id", "Id", companyJobSkills.Job);
            return View(companyJobSkills);
        }

        // GET: CompanyJobSkills/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobSkills = await _context.CompanyJobSkills
                .Include(c => c.JobNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyJobSkills == null)
            {
                return NotFound();
            }

            return View(companyJobSkills);
        }

        // POST: CompanyJobSkills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var companyJobSkills = await _context.CompanyJobSkills.FindAsync(id);
            _context.CompanyJobSkills.Remove(companyJobSkills);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyJobSkillsExists(Guid id)
        {
            return _context.CompanyJobSkills.Any(e => e.Id == id);
        }
    }
}

Controllers/SecurityLoginsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CareerCloudMVCCore2.Models;

namespace CareerCloudMVCCore2.Controllers
{
    public class SecurityLoginsController : Controller
    {
        private readonly JOB_PORTAL_DBContext _context;

        public SecurityLoginsController(JOB_PORTAL_DBContext context)
        {
            _context = context;
        }

        // GET: SecurityLogins
        public async Task<IActionResult> Index()
        {
            return View(await _context.SecurityLogins.ToListAsync());
        }

        // GET: SecurityLogins/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var securityLogins = await _context.SecurityLogins
                .FirstOrDefaultAsync(m => m.Id == id);
            if (securityLogins == null)
            {
                return NotFound();
            }

            return View(securityLogins);
        }

        // GET: SecurityLogins/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SecurityLogins/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Login,Password,CreatedDate,PasswordUpdateDate,AgreementAcceptedDate,IsLocked,IsInactive,EmailAddress,PhoneNumber,FullName,ForceChangePassword,PrefferredLanguage,TimeStamp")] SecurityLogins securityLogins)
        {
            if (ModelState.IsValid)
            {
                securityLogins.Id = Guid.NewGuid();
                _context.Add(securityLogins);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return RedirectToAction(nameof(Create), "ApplicantProfiles", new { id = securityLogins.Id });
            }
            return View(securityLogins);
        }

        // GET: SecurityLogins/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var securityLogins = await _context.SecurityLogins.FindAsync(id);
            if (securityLogins == null)
            {
                return NotFound();
            }
            return View(securityLogins);
        }

        // POST: SecurityLogins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Login,Password,CreatedDate,PasswordUpdateDate,AgreementAcceptedDate,IsLocked,IsInactive,EmailAddress,PhoneNumber,FullName,ForceChangePassword,PrefferredLanguage,TimeStamp")] SecurityLogins securityLogins)
        {
            if (id != securityLogins.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(securityLogins);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SecurityLoginsExists(securityLogins.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(securityLogins);
        }

        // GET: SecurityLogins/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var securityLogins = await _context.SecurityLogins
                .FirstOrDefaultAsync(m => m.Id == id);
            if (securityLogins == null)
            {
                return NotFound();
            }

            return View(securityLogins);
        }

        // POST: SecurityLogins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var securityLogins = await _context.SecurityLogins.FindAsync(id);
            _context.SecurityLogins.Remove(securityLogins);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SecurityLoginsExists(Guid id)
        {
            return _context.SecurityLogins.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Applicants.cshtml
@model IEnumerable<CareerCloudMVCCore2.Models.ApplicantJobApplications>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicantNavigation.LoginNavigation.FullName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicantNavigation.LoginNavigation.FullName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_CompanyDescriptions.cshtml
@model IEnumerable<CareerCloudMVCCore2.Models.CompanyDescriptions>

    <p>
        @*<a asp-action="Create">Create New</a>*@
        <h1>Company Description</h1>
    </p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Language)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyNavigation.ContactPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Language.LanguageId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_CompanyJobDescriptions.cshtml
@model IEnumerable<CareerCloudMVCCore2.Models.CompanyJobsDescriptions>

<p>
    <h1>Job Description</h1>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobDescriptions)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.JobName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobDescriptions)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_CompanyJobEducations.cshtml
@model IEnumerable<CareerCloudMVCCore2.Models.CompanyJobEducations>

<p>
    <h1>Education Requirements</h1>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Major)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Importance)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Major)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Importance)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_CompanyJobSkills.cshtml
@model IEnumerable<CareerCloudMVCCore2.Models.CompanyJobSkills>

<p>
    <h1>Skill requirements</h1>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Skill)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SkillLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Importance)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Skill)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SkillLevel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Importance)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_CompanyJobs.cshtml
@model IEnumerable<CareerCloudMVCCore2.Models.CompanyJobs>

    <p>

        <h1>Company Jobs</h1>
        <a asp-controller="CompanyJobs" asp-action="Create" asp-route-id=@ViewData["Id"]>Create New</a>
    </p>
<table class="table">
    <thead>
        <tr>
            <th>
                JOBS
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @foreach (var job in item.CompanyJobsDescriptions)
                {
                    @Html.ActionLink(job.JobName, "Details", "CompanyJobs", new { Id = item.Id })
                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                @*@Html.Partial("_CompanyJobSkills",item.CompanyJobSkills);*@
            @*<a asp-controller="CompanyJobSkills" asp-action="SkillDetails" asp-route-id="@item.Id">Skill Details</a> |*@
            @*<a asp-controller="CompanyJobEducations" asp-action="EducationDetails" asp-route-id="@item.Id">Education Details</a> |
            <a asp-controller="CompanyJobsDescriptions" asp-action="JobDescriptionDetails" asp-route-id="@item.Id">Job Description</a>*@
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_CompanyLocations.cshtml
@model IEnumerable<CareerCloudMVCCore2.Models.CompanyLocations>

@{
    ViewData["Title"] = "Index";
}

<h1>Company Locations</h1>

<p>
    @*<a asp-action="Create">Create New</a>*@
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CountryCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StateProvinceCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StreetAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CityTown)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZipPostalCode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CountryCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StateProvinceCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StreetAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CityTown)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ZipPostalCode)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CareerCloud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style=" background-color:lightpink">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CareerCloud</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApplicantProfiles" asp-action="Index">Applicant Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CompanyProfiles" asp-action="Index">Employee Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SecurityLogins" asp-action="Create">New Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CareerCloud by Mahdis Moazen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>