Models/CompanyProfiles.cs
using System;
using System.Collections.Generic;

namespace CareerCloudMVCCore2.Models
{
    public partial class CompanyProfiles
    {
        public CompanyProfiles()
        {
            CompanyDescriptions = new HashSet<CompanyDescriptions>();
            CompanyJobs = new HashSet<CompanyJobs>();
            CompanyLocations = new HashSet<CompanyLocations>();
        }

        public Guid Id { get; set; }
        public DateTime RegistrationDate { get; set; }
        public string CompanyWebsite { get; set; }
        public string ContactPhone { get; set; }
        public string ContactName { get; set; }
        public byte[] CompanyLogo { get; set; }
        public byte[] TimeStamp { get; set; }

        public virtual ICollection<CompanyDescriptions> CompanyDescriptions { get; set; }
        public virtual ICollection<CompanyJobs> CompanyJobs { get; set; }
        public virtual ICollection<CompanyLocations> CompanyLocations { get; set; }
    }
}

Controllers/CompanyProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CareerCloudMVCCore2.Models;
using CareerCloudMVCCore2.Models.ViewModel;

namespace CareerCloudMVCCore2.Controllers
{
    public class CompanyProfilesController : Controller
    {
        private readonly JOB_PORTAL_DBContext _context;

        public CompanyProfilesController(JOB_PORTAL_DBContext context)
        {
            _context = context;
        }

        // GET: CompanyProfiles
        public async Task<IActionResult> Index()
        {
            var companyProfiles = await _context.CompanyProfiles
                .Include(cd=>cd.CompanyDescriptions)
                .ToListAsync();

            //var viewModel = new ViewModel();
            //viewModel.CompanyProfiles = _context.CompanyProfiles
            //    .Include(a => a.CompanyDescriptions)
            //    .ToList();


            return View(companyProfiles);
        }

        // GET: CompanyProfiles/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyProfiles = await _context.CompanyProfiles
                .Include(a=>a.CompanyLocations)
                .Include(a=>a.CompanyDescriptions)
                .Include(a=>a.CompanyJobs).ThenInclude(a => a.CompanyJobSkills)
                .Include(a=>a.CompanyJobs).ThenInclude(a=> a.CompanyJobsDescriptions)
                .Include(a=>a.CompanyJobs).ThenInclude(a=> a.CompanyJobEducations)
                .FirstOrDefaultAsync(m => m.Id == id);

            //_context.Entry(companyProfiles).Collection(c => c.CompanyJobs).Load();

            if (companyProfiles == null)
            {
                return NotFound();
            }

            return View(companyProfiles);
        }

        // GET: CompanyProfiles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CompanyProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RegistrationDate,CompanyWebsite,ContactPhone,ContactName,CompanyLogo")] CompanyProfiles companyProfiles)
        {
            if (ModelState.IsValid)
            {
                companyProfiles.Id = Guid.NewGuid();
                _context.Add(companyProfiles);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return RedirectToAction(nameof(Create), "CompanyDescriptions", new { id = companyProfiles.Id });
            }
            return View(companyProfiles);
        }

        // GET: CompanyProfiles/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyProfiles = await _context.CompanyProfiles.FindAsync(id);
            if (companyProfiles == null)
            {
                return NotFound();
            }
            return View(companyProfiles);
        }

        // POST: CompanyProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,RegistrationDate,CompanyWebsite,ContactPhone,ContactName,CompanyLogo,TimeStamp")] CompanyProfiles companyProfiles)
        {
            if (id != companyProfiles.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(companyProfiles);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyProfilesExists(companyProfiles.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(companyProfiles);
        }

        // GET: CompanyProfiles/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyProfiles = await _context.CompanyProfiles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyProfiles == null)
            {
                return NotFound();
            }

            return View(companyProfiles);
        }

        // POST: CompanyProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var companyProfiles = await _context.CompanyProfiles.FindAsync(id);
            _context.CompanyProfiles.Remove(companyProfiles);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyProfilesExists(Guid id)
        {
            return _context.CompanyProfiles.Any(e => e.Id == id);
        }
    }
}

Views/CompanyProfiles/Create.cshtml
@model CareerCloudMVCCore2.Models.CompanyProfiles

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CompanyProfiles</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegistrationDate" class="control-label"></label>
                <input asp-for="RegistrationDate" class="form-control" />
                <span asp-validation-for="RegistrationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyWebsite" class="control-label"></label>
                <input asp-for="CompanyWebsite" class="form-control" />
                <span asp-validation-for="CompanyWebsite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPhone" class="control-label"></label>
                <input asp-for="ContactPhone" class="form-control" />
                <span asp-validation-for="ContactPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactName" class="control-label"></label>
                <input asp-for="ContactName" class="form-control" />
                <span asp-validation-for="ContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyLogo" class="control-label"></label>
                <input asp-for="CompanyLogo" class="form-control" />
                <span asp-validation-for="CompanyLogo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Company Description" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CompanyProfiles/Delete.cshtml
@model CareerCloudMVCCore2.Models.CompanyProfiles

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompanyProfiles</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyWebsite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyWebsite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyLogo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyLogo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/CompanyProfiles/Details.cshtml
@model CareerCloudMVCCore2.Models.CompanyProfiles

@{
    ViewData["Title"] = "Details";
}

@*<h1>Company Details</h1>*@

@*<div>
    <h4>CompanyProfiles</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyWebsite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyWebsite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactName)
        </dd>
    </dl>
</div>*@
<div>
    @Html.Partial("_CompanyLocations", Model.CompanyLocations) 
</div>
<div>
    @Html.Partial("_CompanyDescriptions", Model.CompanyDescriptions)
</div>
<div>
    @Html.Partial("_CompanyJobs", Model.CompanyJobs,new ViewDataDictionary(ViewData) { { "Id", Model.Id } })
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/CompanyProfiles/Edit.cshtml
@model CareerCloudMVCCore2.Models.CompanyProfiles

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CompanyProfiles</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="RegistrationDate" class="control-label"></label>
                <input asp-for="RegistrationDate" class="form-control" />
                <span asp-validation-for="RegistrationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyWebsite" class="control-label"></label>
                <input asp-for="CompanyWebsite" class="form-control" />
                <span asp-validation-for="CompanyWebsite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPhone" class="control-label"></label>
                <input asp-for="ContactPhone" class="form-control" />
                <span asp-validation-for="ContactPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactName" class="control-label"></label>
                <input asp-for="ContactName" class="form-control" />
                <span asp-validation-for="ContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyLogo" class="control-label"></label>
                <input asp-for="CompanyLogo" class="form-control" />
                <span asp-validation-for="CompanyLogo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CompanyProfiles/Index.cshtml
@model IEnumerable<CareerCloudMVCCore2.Models.CompanyProfiles>
@*@model CareerCloudMVCCore2.Models.ViewModel.ViewModel*@

@{
    ViewData["Title"] = "Index";
}

<h1>Company List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RegistrationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyWebsite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactName)
            </th>
            <th>
                <h6>
                    Company Name
                </h6>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyWebsite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactName)
            </td>
            <td>
                @foreach(var item2 in item.CompanyDescriptions.Where(L=>L.LanguageId.Trim()=="EN"))
                {
                    @Html.ActionLink(item2.CompanyName,"Details","CompanyProfiles",new{Id=item.Id})
                 }
            </td>
 
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
,