Models/CompanyJobs.cs
using System;
using System.Collections.Generic;

namespace CareerCloudMVCCore2.Models
{
    public partial class CompanyJobs
    {
        public CompanyJobs()
        {
            ApplicantJobApplications = new HashSet<ApplicantJobApplications>();
            CompanyJobEducations = new HashSet<CompanyJobEducations>();
            CompanyJobSkills = new HashSet<CompanyJobSkills>();
            CompanyJobsDescriptions = new HashSet<CompanyJobsDescriptions>();
        }

        public Guid Id { get; set; }
        public Guid Company { get; set; }
        public DateTime ProfileCreated { get; set; }
        public bool IsInactive { get; set; }
        public bool IsCompanyHidden { get; set; }
        public byte[] TimeStamp { get; set; }

        public virtual CompanyProfiles CompanyNavigation { get; set; }
        public virtual ICollection<ApplicantJobApplications> ApplicantJobApplications { get; set; }
        public virtual ICollection<CompanyJobEducations> CompanyJobEducations { get; set; }
        public virtual ICollection<CompanyJobSkills> CompanyJobSkills { get; set; }
        public virtual ICollection<CompanyJobsDescriptions> CompanyJobsDescriptions { get; set; }
    }
}

Controllers/CompanyJobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CareerCloudMVCCore2.Models;

namespace CareerCloudMVCCore2.Controllers
{
    public class CompanyJobsController : Controller
    {
        private readonly JOB_PORTAL_DBContext _context;

        public CompanyJobsController(JOB_PORTAL_DBContext context)
        {
            _context = context;
        }

        // GET: CompanyJobs
        public async Task<IActionResult> Index(Guid Applicant)
        {
            var jOB_PORTAL_DBContext = _context.CompanyJobs
                .Include(a=>a.CompanyJobsDescriptions)
                .Include(a=>a.CompanyJobEducations)
                .Include(a=>a.CompanyJobSkills)
                .Include(c => c.CompanyNavigation)
                   .ThenInclude(a=>a.CompanyDescriptions);
            ViewData["Applicant"] = Applicant;
            return View(await jOB_PORTAL_DBContext.ToListAsync());
        }

        // GET: CompanyJobs/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobs = await _context.CompanyJobs
                .Include(a=>a.CompanyJobsDescriptions)
                .Include(a=>a.CompanyJobEducations)
                .Include(a=>a.CompanyJobSkills)
                .Include(a=>a.ApplicantJobApplications)
                  .ThenInclude(a=>a.ApplicantNavigation)
                    .ThenInclude(a=>a.LoginNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyJobs == null)
            {
                return NotFound();
            }

            return View(companyJobs);
        }

        // GET: CompanyJobs/Create
        public IActionResult Create(Guid id)
        {
            ViewData["Company"] = new SelectList(_context.CompanyProfiles, "Id", "ContactPhone");
            return View();
        }

        // POST: CompanyJobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Company,ProfileCreated,IsInactive,IsCompanyHidden")] CompanyJobs companyJobs,Guid id)
        {
            companyJobs.Company = id;
            if (ModelState.IsValid)
            {
                companyJobs.Id = Guid.NewGuid();
                _context.Add(companyJobs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create),"CompanyJobsDescriptions",new {id=companyJobs.Id});
            }
            ViewData["Company"] = new SelectList(_context.CompanyProfiles, "Id", "ContactPhone", companyJobs.Company);
            return View(companyJobs);
        }

        // GET: CompanyJobs/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobs = await _context.CompanyJobs.FindAsync(id);
            if (companyJobs == null)
            {
                return NotFound();
            }
            ViewData["Company"] = new SelectList(_context.CompanyProfiles, "Id", "ContactPhone", companyJobs.Company);
            return View(companyJobs);
        }

        // POST: CompanyJobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Company,ProfileCreated,IsInactive,IsCompanyHidden,TimeStamp")] CompanyJobs companyJobs)
        {
            if (id != companyJobs.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(companyJobs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyJobsExists(companyJobs.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Company"] = new SelectList(_context.CompanyProfiles, "Id", "ContactPhone", companyJobs.Company);
            return View(companyJobs);
        }

        // GET: CompanyJobs/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobs = await _context.CompanyJobs
                .Include(c => c.CompanyNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyJobs == null)
            {
                return NotFound();
            }

            return View(companyJobs);
        }

        // POST: CompanyJobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var companyJobs = await _context.CompanyJobs.FindAsync(id);
            _context.CompanyJobs.Remove(companyJobs);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ForApplicantDetails(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyJobs = await _context.CompanyJobs
                .Include(a=>a.CompanyNavigation)
                .Include(a => a.CompanyJobsDescriptions)
                .Include(a => a.CompanyJobEducations)
                .Include(a => a.CompanyJobSkills)
                .Include(a => a.ApplicantJobApplications)
                  .ThenInclude(a => a.ApplicantNavigation)
                    .ThenInclude(a => a.LoginNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (companyJobs == null)
            {
                return NotFound();
            }

            return View(companyJobs);
        }
        private bool CompanyJobsExists(Guid id)
        {
            return _context.CompanyJobs.Any(e => e.Id == id);
        }
    }
}

Views/CompanyJobs/Create.cshtml
@model CareerCloudMVCCore2.Models.CompanyJobs

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CompanyJobs</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            @*<div class="form-group">
                <label asp-for="Company" class="control-label"></label>
                <select asp-for="Company" class ="form-control" asp-items="ViewBag.Company"></select>
            </div>*@
            <div class="form-group">
                <label asp-for="ProfileCreated" class="control-label"></label>
                <input asp-for="ProfileCreated" class="form-control" />
                <span asp-validation-for="ProfileCreated" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsInactive" /> @Html.DisplayNameFor(model => model.IsInactive)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCompanyHidden" /> @Html.DisplayNameFor(model => model.IsCompanyHidden)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Job Description" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CompanyJobs/Delete.cshtml
@model CareerCloudMVCCore2.Models.CompanyJobs

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompanyJobs</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfileCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfileCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsInactive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsInactive)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompanyHidden)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCompanyHidden)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyNavigation.ContactPhone)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/CompanyJobs/Details.cshtml
@model CareerCloudMVCCore2.Models.CompanyJobs

@{
    ViewData["Title"] = "Details";
}

@*<h1>Job Details</h1>*@

@*<div>
    <h4>CompanyJobs</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfileCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfileCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsInactive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsInactive)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompanyHidden)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCompanyHidden)
        </dd>
    </dl>
</div>*@
<div>
    @Html.Partial("_CompanyJobDescriptions", Model.CompanyJobsDescriptions)
</div>
<div>
    @Html.Partial("_CompanyJobSkills", Model.CompanyJobSkills)
</div>
<div>
    @Html.Partial("_CompanyJobEducations", Model.CompanyJobEducations)
</div>
<div>
    @Html.Partial("_Applicants", Model.ApplicantJobApplications)
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/CompanyJobs/Edit.cshtml
@model CareerCloudMVCCore2.Models.CompanyJobs

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CompanyJobs</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Company" class="control-label"></label>
                <select asp-for="Company" class="form-control" asp-items="ViewBag.Company"></select>
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfileCreated" class="control-label"></label>
                <input asp-for="ProfileCreated" class="form-control" />
                <span asp-validation-for="ProfileCreated" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsInactive" /> @Html.DisplayNameFor(model => model.IsInactive)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCompanyHidden" /> @Html.DisplayNameFor(model => model.IsCompanyHidden)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CompanyJobs/ForApplicantDetails.cshtml
@model CareerCloudMVCCore2.Models.CompanyJobs

@{
    ViewData["Title"] = "ForApplicantDetails";
}

@*<h1>Job Details</h1>*@

@*<div>
        <h4>CompanyJobs</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.ProfileCreated)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.ProfileCreated)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.IsInactive)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.IsInactive)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.IsCompanyHidden)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.IsCompanyHidden)
            </dd>
        </dl>
    </div>*@
<div>
    @Html.Partial("_CompanyJobDescriptions", Model.CompanyJobsDescriptions)
</div>
<div>
    @Html.Partial("_CompanyJobSkills", Model.CompanyJobSkills)
</div>
<div>
    @Html.Partial("_CompanyJobEducations", Model.CompanyJobEducations)
</div>

Views/CompanyJobs/Index.cshtml
@model IEnumerable<CareerCloudMVCCore2.Models.CompanyJobs>

<table class="table">
    <thead>
        <tr>
            <th>
                Company
            </th>
            <th>
                jOBS
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @foreach (var item2 in item.CompanyNavigation.CompanyDescriptions.Where(L => L.LanguageId.Trim() == "EN"))
                {
                    @Html.ActionLink(item2.CompanyName, "Details", "CompanyProfiles", new { Id = item.Company})
                }
            </td>
            <td>
                @foreach (var job in item.CompanyJobsDescriptions)
                {
                    @Html.ActionLink(job.JobName, "ForApplicantDetails", "CompanyJobs", new { Id = item.Id })
                }
            </td>
            <td>
                <a asp-action="Create" asp-controller="ApplicantJobApplications" asp-route-Job="@item.Id"
                   asp-route-Applicant="@ViewData["Applicant"]">Apply</a> |
              
                @*<a asp-action="Details" asp-route-id="@item.Id">Details</a> 
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@ 
                @*@Html.Partial("_CompanyJobSkills",item.CompanyJobSkills);*@
                @*<a asp-controller="CompanyJobSkills" asp-action="SkillDetails" asp-route-id="@item.Id">Skill Details</a> |*@
                @*<a asp-controller="CompanyJobEducations" asp-action="EducationDetails" asp-route-id="@item.Id">Education Details</a> 
            <a asp-controller="CompanyJobsDescriptions" asp-action="JobDescriptionDetails" asp-route-id="@item.Id">Job Description</a>*@
            </td>
        </tr>
        }
    </tbody>
</table>